### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by gbdavidx** [geekofweek/homeassistant#15]
I am using some of your light automations, what is this?

I have an insteon switch for my patio, i am able to turn it on automatically, but upon following your automation for turning it off i am a bit confused on your conditions
  ```
condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_exterior_off_night
      state: 'off'
#    - condition: not
#      conditions:
#      - condition: state
#        entity_id: group.friends_and_family
#       state: 'home'
```

**Comment by gbdavidx** [comment]
i understand that it must be dark, but what is the 2nd and 3rd condition? can you explain like im 5?

**Comment by geekofweek** [comment]
```
  - condition: state
    entity_id: input_boolean.disable_exterior_off_night
    state: 'off'
```
This is an input_boolean that I use as a toggle over-ride.  So if I toggle the disable it won't fire the automation.  I reset all the over-rides each morning.  Gives me a way to easy control a swath of automations not running for testing or whatever purpose.

```
    - condition: not
      conditions:
      - condition: state
        entity_id: group.friends_and_family
       state: 'home'

```

This is a condition not statement.  Basically I have a friends and family group, aka guests, if they are anything other than home run the automation.  This disables turning off my landscape lighting if I have guests over.
